apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: django-secrets
  namespace: notes-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: django-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/notes-app
