apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notes-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/DevoopsDev/django-notes-app.git
    targetRevision: main
    path: k8s/notes-app

  destination:
    server: https://kubernetes.default.svc
    namespace: notes-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
